# Generated by Django 5.1.6 on 2025-10-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='asif',
        ),
    ]
